# development - local
version: '3'

services:
  storage:
    container_name: partydeck-panel
    restart: always
    build:
      context: .
      args:
        - MONGO_URI=mongodb://mongo:27017/partydecks
        - JWT_SECRET=abcdefghijkkmnop
        - SERVER_URL=http://localhost:8000
        - GAME_URL=http://localhost:3001
    ports:
      - '4000:4000'
    external_links:
      - 'mongo'
    environment:
      - PORT=4000
      - LIMIT_GAMES=false
      - SECURE=false #modify later
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27018:27017' # no need for this later
    volumes:
      - './storage/data/db:/data/db'
  server:
    container_name: partydeck-live
    restart: always
    build: ./server
    ports:
      - '8000:8000'
    environment:
      - PORT=8000
      - CONSOLE=true
  game:
    container_name: patrydeck-live-game-frontend
    restart: always
    build:
      context: ./game
      args:
        - REACT_APP_SERVER_URL=http://localhost:8000
        - REACT_APP_SERVER_WS=ws://localhost:8000
    ports:
      - '3001:3001'
    external_links:
      - 'server'
