import { useState } from 'react';

export function useGame(gameId) {
  const [game, setGame] = useState({
    _id: gameId,
    lng: 'en',
    name: 'A Random Deck',
    isPrivate: false,
    author: { name: 'Itay', _id: '1' },
    questions: [
      'question',
      'question',
      'question',
      'question',
      'question',
      'question',
      'question',
      'question',
      'question',
      'question',
      'question',
      'question',
      'question',
      'question',
      'question',
      'question',
      'question',
      'question',
      'question',
      'question',
      'question',
      'question',
      'question',
      'question',
    ],
    answers: [
      'answer',
      'answer',
      'answer',
      'answer',
      'answer',
      'answer',
      'answer',
      'answer',
      'answer',
      'answer',
      'answer',
      'answer',
      'answer',
      'answer',
      'answer',
      'answer',
      'answer',
      'answer',
      'answer',
      'answer',
      'answer',
      'answer',
      'answer',
      'answer',
      'answer',
    ],
  });

  return {
    game,
  };
}
