export function useGame(gameId) {
  return {
    _id: gameId,
    lng: 'en',
    name: 'A Random Deck',
    isPrivate: false,
    author: { name: 'Itay' },
    questions: [
      'question',
      'question',
      'question',
      'question',
      'question',
      'question',
      'question',
      'question',
      'question',
      'question',
      'question',
      'question',
      'question',
      'question',
      'question',
      'question',
      'question',
      'question',
      'question',
      'question',
      'question',
      'question',
      'question',
      'question',
    ],
    answers: [
      'answer',
      'answer',
      'answer',
      'answer',
      'answer',
      'answer',
      'answer',
      'answer',
      'answer',
      'answer',
      'answer',
      'answer',
      'answer',
      'answer',
      'answer',
      'answer',
      'answer',
      'answer',
      'answer',
      'answer',
      'answer',
      'answer',
      'answer',
      'answer',
      'answer',
    ],
  };
}
